### ISSUE TITLE
Update Maintenance Configuration to Use Environment Variables

### ISSUE THREAD

**Issue by wawoxe** [wawoxe/MaintenanceBundle#1]
**Current Configuration:**

```yaml
# Configuration file for MaintenanceBundle.
# Contains parameters and service definitions.

parameters:
  # Indicates whether maintenance mode is enabled.
  # Set to true to enable maintenance mode, false otherwise.
  app.maintenance.enabled: true

  # Priority of the maintenance event listener.
  # Determines the order in which event listeners are executed.
  app.maintenance.priority: 1000

services:
  # Maintenance response service definition.
  maintenance_response:
    # Class responsible for generating maintenance responses.
    class: Wawoxe\MaintenanceBundle\Response\MaintenanceDefaultResponse

  # Maintenance event listener service definition.
  Wawoxe\MaintenanceBundle\EventListener\MaintenanceListener:
    # Tags the service as an event listener for the 'kernel.request' event.
    # The listener's priority is determined by the value of 'app.maintenance.priority'.
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: '%app.maintenance.priority%' }
    # Constructor arguments for the maintenance event listener.
    # Injects the maintenance response service and the value of 'app.maintenance.enabled'.
    arguments:
      - '@maintenance_response'
      - '%app.maintenance.enabled%'
```

**Proposed Changes:**

Currently, the maintenance mode configuration is hardcoded within the services.yaml file. To enhance flexibility and manageability, I propose migrating the configuration to utilize environment variables.

**Proposed Configuration:**

```yaml
# Configuration file for MaintenanceBundle.
# Contains parameters and service definitions.

parameters:
  # Indicates whether maintenance mode is enabled.
  # Set to true to enable maintenance mode, false otherwise.
  env(MAINTENANCE_MODE): 'false'
  maintenance.mode: '%env(bool:MAINTENANCE_MODE)%'

  # Priority of the maintenance event listener.
  # Determines the order in which event listeners are executed.
  env(MAINTENANCE_PRIORITY): 1000
  maintenance.priority: '%env(int:MAINTENANCE_PRIORITY)%'

services:
  # Maintenance response service definition.
  maintenance_response:
    # Class responsible for generating maintenance responses.
    class: Wawoxe\MaintenanceBundle\Response\MaintenanceDefaultResponse

  # Maintenance event listener service definition.
  Wawoxe\MaintenanceBundle\EventListener\MaintenanceListener:
    # Tags the service as an event listener for the 'kernel.request' event.
    # The listener's priority is determined by the value of 'maintenance.priority'.
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: '%maintenance.priority%' }
    # Constructor arguments for the maintenance event listener.
    # Injects the maintenance response service and the value of 'maintenance.mode'.
    arguments:
      - '@maintenance_response'
      - '%maintenance.mode%'
```

**Steps to Implement:**

1. Refactor the `config/services.yaml` file to utilize environment variables for maintenance mode and priority settings.
2. Ensure that the `symfony/dotenv` component is installed to enable the use of environment variables in Symfony applications.
3. Update the documentation to reflect the changes made and provide guidance on setting up the necessary environment variables.
